"""add error embedding

Revision ID: 00f49c99f17b
Revises: a1dfbbd2a84a
Create Date: 2026-05-06 13:44:03.026102

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import Vector

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00f49c99f17b'
down_revision: Union[str, Sequence[str], None] = 'a1dfbbd2a84a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('errors', sa.Column('embedding', Vector(1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('errors', 'embedding')
    # ### end Alembic commands ###
