"""add error details

Revision ID: 6c744db3e98c
Revises: 16f13e4b8293
Create Date: 2026-05-04 18:42:52.723796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c744db3e98c'
down_revision: Union[str, Sequence[str], None] = '16f13e4b8293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(

    'errors',

    sa.Column('level', sa.String(length=50), nullable=False, server_default='error')

)
    op.add_column('errors', sa.Column('stack_trace', sa.String(), nullable=True))
    op.add_column('errors', sa.Column('source', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('errors', 'source')
    op.drop_column('errors', 'stack_trace')
    op.drop_column('errors', 'level')
    # ### end Alembic commands ###
