"""add error grouping

Revision ID: a1dfbbd2a84a
Revises: 6c744db3e98c
Create Date: 2026-05-05 10:06:14.292188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1dfbbd2a84a'
down_revision: Union[str, Sequence[str], None] = '6c744db3e98c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signature', sa.String(length=255), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_groups_signature'), 'error_groups', ['signature'], unique=True)
    op.add_column('errors', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'errors', 'error_groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'errors', type_='foreignkey')
    op.drop_column('errors', 'group_id')
    op.drop_index(op.f('ix_error_groups_signature'), table_name='error_groups')
    op.drop_table('error_groups')
    # ### end Alembic commands ###
